### ISSUE TITLE
Package.json contains internal SAP reference

### ISSUE THREAD

**Issue by jonathanbaker7** [SAP/utils-pptx-templater#1]
The file [package.json](https://github.com/SAP/utils-pptx-templater/blob/5485e3820007ff99b0749273c834fcc36283dd0a/package.json) contains a reference to an internal SAP server:

    "url": "git@github.wdf.sap.corp:rapid-release/pptxtemplater.git"

Specifically, the server:

    github.wdf.sap.corp

This artifact won't work outside the SAP firewall.

SAP Open Source runs regular scans looking for artifacts in the code which might indicate our internal code has accidentally released in to the Open Source stream. This file continues to show up in our scans. Can you please fix it, or remove it, so that it no longer shows up as an error?

Thank you.

**Comment by KharitonOff** [comment]
Thanks for pointing this out!
